services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync+restart
          path: ./backend/src
          target: /app/src

  frontend:
    build:
      context: ./frontend
    environment:
      BACKEND_URL: http://backend:3000
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
    depends_on:
      - backend